[package]
name = "nonce_accs_investigate"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-sdk = "2"
solana-client = "2"
solana-program = "2"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
bincode = "1"
futures = "0.3"
